### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by csf30816** [InfinityFreeHosting/mofh-client#16]
I do not have composer and I do not plan on getting it, can you tell me which files/directories I need to copy?

**Comment by Grendel7** [comment]
In theory, you could download everything in the `src/` folder and `require_once` all files in it. It's not pretty and not supported.

Alternatively, you could look for some way to mimic the Composer autoload functionality (I know there are other, similar autoloader scripts).

However, Composer is the only supported installation method right now and I personally have no interest in adding alternative installation methods. I do accept pull requests though, if you can figure out a way to cleanly import the library without polluting the main codebase or breaking Composer compatibility.

**Comment by Rayhansardar420** [comment]
Bro,Hope this will help you.


https://php-download.com/package/hansadema/mofh-client

**Comment by Grendel7** [comment]
@Rayhansardar420 The site you links to looks useful, but it still uses Composer (it just runs the `composer install` for you and doesn't require you to run Composer yourself). I'm not sure whether that actually qualifies as installing "without Composer".

**Comment by GoogleOnScratch** [comment]
@Rayhansardar420 That should work, thanks.

**Note:** I just had the same problem as @csf30816, I am not talking for him :D

**Comment by csf30816** [comment]
Hello. Thanks @Rayhansardar420, although this gave me a 500 error when I installed on my server

Edit:
====
Fixed
