### ISSUE TITLE
What Do you mean by $domain

### ISSUE THREAD

**Issue by Rayhansardar420** [InfinityFreeHosting/mofh-client#17]
Hi,there!

I am now just testing the  script.But host should I write the domain string.

For examle, I have my reseller domain geoweb.host and want to test  of rayhan.geoweb.host is availabe.

So how do I do this. An example would best.If any of you would kindly share an example it would very nice.

Thanks.

**Comment by Grendel7** [comment]
Which API call are you referring to?

Everywhere in this client, `domain` is used to refer to a FQDN. That's not just something you can buy at a registrar, subdomains are FQDNs as well.
