### ISSUE TITLE
Is it supposed to do this?

### ISSUE THREAD

**Issue by csf30816** [InfinityFreeHosting/mofh-client#19]
I ran this code in PHP:
```
print_r($client->availability("domain.com"));
```
but it returns `1` every time I try to do it. Even when I select a domain that is available.

**Comment by Grendel7** [comment]
The function will return `true` or `1` if the domain name is available to be added to a hosting account and `false` or `0` if not. Try checking a domain name which you know is already parked on MyOwnFreeHost.

**Comment by csf30816** [comment]
@HansAdema OK. Also does the create account function return the cpanel username like `blah_12345678`?

**Comment by Grendel7** [comment]
@csf30816 If you're using the 0.1.* versions, then that's the only thing the createAccount function returns. If you're using a 0.2.* version, you can get the username with `$response->getVpUsername();`.

**Comment by csf30816** [comment]
OK, what else does it return for 0.2.* (I am using 0.1.* just courious)

**Comment by Grendel7** [comment]
@csf30816 It doesn't really return anything else, the format is just different. The API just doesn't return any useful data. You can see an example response here: https://github.com/HansAdema/mofh-client/blob/bb8ab01a400d2e5476a901b1d3a3173746b30e27/tests/Message/CreateAccountRequestTest.php#L47

If you see anything you think might be useful, then I can see about adding it. But the username is the only thing I've found useful myself.

**Comment by csf30816** [comment]
OK thanks!
