### ISSUE TITLE
Fatal error: Class 'AbstractRequest' not found in F:\xamp\htdocs\w\moh\mofh-client-master\src\Message\CreateAccountRequest.php on line 6

### ISSUE THREAD

**Issue by osmanfc** [InfinityFreeHosting/mofh-client#21]
Fatal error: Class 'AbstractRequest' not found in F:\xamp\htdocs\w\moh\mofh-client-master\src\Message\CreateAccountRequest.php on line 6
how can solve it

**Comment by Grendel7** [comment]
Did you install the library with Composer?

**Comment by osmanfc** [comment]
No! How install Compreser In Shared Hosting Please Tell me

**Comment by csf30816** [comment]
@osmanfc You can not
use https://php-download.com/package/hansadema/mofh-client instead

**Comment by Grendel7** [comment]
@osmanfc That depends on whether your shared hosting provider supports SSH. If they support SSH and you can execute PHP commands on the command line, you could probably use Composer. If not, you can use the tool recommended by @csf30816 .
