### ISSUE TITLE
Support API

### ISSUE THREAD

**Issue by csf30816** [InfinityFreeHosting/mofh-client#22]
Could you make a function to get the Support Questions and to reply to support questions. Because I would like to create a mobile app for the supporters that let's them view all the messages and reply to the messages. Thanks :)

**Comment by csf30816** [comment]
I guess I could make my own support platform with an API if this is not possible, it is just easier to keep it to one API :)

**Comment by Rayhansardar420** [comment]
As you are not using default  myownfreehost.net api rather cpanel api.

You could always bulid a special support system in php on your live site.

It will be kind of like whmcs.

And cpanel doesn't supports support ticket system.It was installed by myownfreehost.net and we are using cpanel api.

So nothing to do I guess.

**Comment by Grendel7** [comment]
Unfortunately, MyOwnFreeHost does not expose the support tickets through their API as far as I know.

If you're going to be coding your own thing around MyOwnFreeHost anyways, I would suggest to build your own support system or to integrate with a separate, existing support solution (like Zendesk or Freshdesk) and just set the support link in VistaPanel.

**Comment by csf30816** [comment]
Yeah, I guess I will have to make my own. (The others either have crappy APIs or are to much moolah). I am always ready for a challenge. Even one for the super friends :/
