### ISSUE TITLE
Incomplete Plan

### ISSUE THREAD

**Issue by csf30816** [InfinityFreeHosting/mofh-client#23]
That title may not make since so here is the problem: When creating an account with the `createAccount` function. I set the plan to `basic` (a plan I created earlier). `basic` has a traffic of `200GB`, a disk of `20GB`, a MYSQL of `40`, and a domain of `20`. Although when I use the PHP to create the account using the plan `basic` it creates an account with the correct MYSQL and Domains but with Traffic set to `209715200GB` and a Disk of `20971520GB`.

I do not know if this is a problem with this or with the MOFH Panel.

**Comment by Grendel7** [comment]
The API client just passes the plan name as-is to the API. It's definitely possible that the plans set through the API don't properly set all the limits properly, but that would be an issue with the API itself. As far as I know, the API does not expose any way to set the resource limits directly.

**Comment by Grendel7** [comment]
I just did a bit of testing myself, and it looks like only the database limit is actually picked up. All the other limits (disk space, bandwidth, domains) all become unlimited.

**Comment by csf30816** [comment]
That is lame

**Comment by Grendel7** [comment]
@csf30816 Yes, it definitely is. You should definitely contact iFastNet about this because this cannot be intentional.

**Comment by csf30816** [comment]
I did but they do not seem to understand what I am talking about :P

**Comment by csf30816** [comment]
Could you do it? You seem to understand the problem more than I...

**Comment by Grendel7** [comment]
This issue should be fixed now.

**Comment by csf30816** [comment]
Awesome :)
