### ISSUE TITLE
Incomplete Plan - Part II

### ISSUE THREAD

**Issue by csf30816** [InfinityFreeHosting/mofh-client#24]
So.. funny thing is... that when I make a plan and check "ad/banner free" when an account gets created it has banner turned on. It does not matter *yet* because I have no banners yet. But I will have a plan with more stuff and ads. So this *will* become a problem. Everything else works :)

**Comment by Grendel7** [comment]
I'll make a note to get this forwarded to the right people.

**Comment by csf30816** [comment]
OK, and thank you.
