### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by systask** [InfinityFreeHosting/mofh-client#26]
Hi,

I've managed to get the mofh-client on my website. Thing is, I'm quite confused. Is there any documentation that I could possibly refer to? Just that I'm quite new to this, and I would like to spend time coding these kinds of projects.

-Eqil

**Comment by Grendel7** [comment]
The [readme](https://github.com/HansAdema/mofh-client/blob/master/README.md) contains some basic documentation and an example. It's a bit basic, but it contains the most important information.

If you find anything to be not clear, please ask a specific question and I'll do my best to clear up any doubt.
