### ISSUE TITLE
Uploaded

### ISSUE THREAD

**Issue by AtomicSlicer** [InfinityFreeHosting/mofh-client#28]
how would we upload using ftp client cause my host does not support composer

**Comment by Grendel7** [comment]
Here is an issue with more information about running without Composer: #16

But again: this tool is designed to be used with Composer. If you are unwilling or unable to use Composer, do so at your own risk.

This issue section is intended for questions or problems regarding this API client. If you cannot understand that, I'll be forced to ban you from opening more issues.
