### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by zero-arc** [InfinityFreeHosting/mofh-client#31]
Just a specific question so I can at least learn or get started. 
Hi, 
First of all thanks for making this!
Second, I understand how to make this but I  need at least some example code so that I can experiment on it.
Can you please give an example code for a sign up form cause I'm not sure how to do it but I have an idea how to make it but still I won't work... 
Please give example..

**Comment by Grendel7** [comment]
The example in the readme might be able to get you started with creating an account: https://github.com/HansAdema/mofh-client#example

I've thought of writing a full signup form example, but there are a lot of questions which this library cannot answer, like:
- Will users sign up with custom domains or subdomain or both?
- How are error messages handled? Are the verbose, typo riddled messages echo-ed verbose or do they need to be parsed? If so, how?
- Will users choose their own alt username or can they enter their own ones?
- What about a CAPTCHA?
- What about email verification (VERY IMPORTANT - DON'T SKIP THIS)?

I'm not sure exactly how we could make a simple example script, which does not contain security holes some ignorant rookie is going to expose to spammers.
