### ISSUE TITLE
Use library in test mode

### ISSUE THREAD

**Issue by crisaldev** [InfinityFreeHosting/mofh-client#32]
hi there, would like to know how to use the api in test mode? I have seen the documentation and it is a little incomplete for people who are not used to using libraries and I would like to know if the library is well installed and I do not want to test directly with the Myownfreehost API when creating the user and see what values it returns to me, thank you very much

**Comment by Grendel7** [comment]
The API does not have a test mode, I'm sorry to say. If iFastNet would add it, I'd be happy to implement it in this client as well. But there is no test mode to switch to right now.
