### ISSUE TITLE
Add to a Client Area already done

### ISSUE THREAD

**Issue by eltiempoenmega** [InfinityFreeHosting/mofh-client#33]
I made a Client Area, but it does not contain this. Could it be added as a php page without doing everything again?

**Comment by Grendel7** [comment]
Please note that this project is a library. It doesn't include any "pages" which you can add to a website.

I don't know if you already have code to connect to MyOwnFreeHost, and I can't decide for you whether you want to use this API client or build/keep your own API wrapper.

**Comment by eltiempoenmega** [comment]
I have a Client Area that does not contain this. Can I add the code without having to rebuild my Client Area?

**Comment by Grendel7** [comment]
That's entirely up to you and your code! If your code is structured in a way you can easily replace the netcode with this client, then you can. If the code is structured in a way you need to change everything to use this client, then you are essentially rebuilding everything.

Seriously, this is an API client. I can't make architectural decisions for your code.

**Comment by eltiempoenmega** [comment]
Thanks :D
