### ISSUE TITLE
3de2e45b14df5fdc36f8607a37c86753

### ISSUE THREAD

**Issue by pauladams8** [InfinityFreeHosting/mofh-client#34]
c6a450b8a1b66c2e78313a3809892dbf

**Comment by Grendel7** [comment]
Did you include `require 'vendor/autoload.php'` at the top of the code? Can you check the vendor folder to ensure the autoload file was actually generated and the client was actually downloaded?

Also, `class_exists` requires the full namespace, so you should check `class_exists('\HansAdema\MofhClient\Client')`: http://php.net/manual/en/function.class-exists.php#113581

Did you actually try instantiating the `Client` class?

**Comment by pauladams24** [comment]
I did include the require line, an autoload.php file was generates and I did try instantiating the `Client` class. Thanks for pointing out my error with `class_exists`, it now returns `works` so the class exists. I have just tried installing it manually through https://php-download.com/code-example/hansadema/mofh-client although I'm still having trouble.

**Comment by pauladams24** [comment]
I have tried `echo $request;` but no output so something is going wrong there.

**Comment by pauladams24** [comment]
This is my full code - `<?php 
error_reporting( E_ALL );
require __DIR__ . '/vendor/autoload.php';
require_once('vendor/autoload.php');
require 'vendor/autoload.php';
use \HansAdema\MofhClient\Client;
if (class_exists('\HansAdema\MofhClient\Client')) { echo "works"; } else { echo "broken"; }
// Create a new API client with your API credentials.
$client = Client::create([
    'apiUsername' => 'XYNzp9wIVGJjc6emkjZSJTLlf4OJf0r389NDCKtwPua67Eyvf8BEBUW1Dc8ZvIXCKAVmSXvSZaRaLuOsUfIa4e5lM44FrIGAUPq7LUGmaQAmN8XaxNQiOlCCDP5csf1qo4lXqLoZCKcfRl8Wy10ZyTZrYrP3x8bONKoZ4bMRDXLMyq8jApPI3hm23vFbSOkCVO2T3NEt2fURgBkI8T55Q09YayOusf9Ogop2iPVgtn7bLxHpC0O2DvU2TESOEId',
    'apiPassword' => 'shE3LX4bimJbUpPTHUsB5701J0mX7YbWPSdPAceR4qE1aNuYaqPTtl6QxHnu7x95JFOjDoHS5bonRfe5uvHIVCYCTojsSmpcgvqkDVAgL3UmLljzqNstz1TpWH12GSnd0rBpEqaeBjBfSOtzU9oys0e77ac1hY9Ju77ZQ6EEOdlWMMvqoiVjfK7INKj4URg8Njay5CT8IxTvx3Veg7m0JPJhlGlIhQI9VVI038Yd4aE5ZdT70ySzpY1C15hUsLl',
    'plan' => 'free', // Optional, you can define it here or define it with the createAccount call.
]);
echo $client;

// Create a request object to create the request.
$request = $client->createAccount([
    'username' => 'abcdefgh', // A unique, 8 character identifier of the account.
    'password' => 'password123', // A password to login to the control panel, FTP and databases.
    'domain' => 'userdomain.example.com', // Can be a subdomain or a custom domain.
    'email' => 'user@example.com', // The email address of the user.
    'plan' => 'my_plan', // Optional, you can submit a hosting plan here or with the Client instantiation.
]);
echo $request;
// Send the API request and keep the response.
$response = $request->send();

// Check whether the request was successful.
if ($response->isSuccessful()) {
   echo 'You can login as: ' . $response->getVpUsername();
} else {
   echo 'Failed to create account: ' . $response->getMessage();
}
?>`

**Comment by Grendel7** [comment]
The URL returns a 500 status code. Check your error logs.

**Comment by pauladams24** [comment]
Sorry do you mean by this the auto load.php file?

**Comment by pauladams24** [comment]
The only error log that looks relevant is as follows:
[Sun Sep 16 06:25:04.762537 2018] [mpm_prefork:notice] [pid 8143] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations 
[Sun Sep 16 06:25:04.762778 2018] [core:notice] [pid 8143] AH00094: Command line: '/usr/sbin/apache2' [Sun Sep 16 09:44:13.768762 2018] 
[:error] [pid 19150] [client 162.158.111.166:23592] PHP Catchable fatal error: Object of class HansAdema\\MofhClient\\Client could not be 
converted to string in /var/www/html/composer/index.php on line 14 [Sun Sep 16 09:44:50.133577 2018] [:error] [pid 19152] [client 
162.158.111.166:59780] PHP Catchable fatal error: Object of class HansAdema\\MofhClient\\Client could not be converted to string in 
/var/www/html/composer/index.php on line 14 [Sun Sep 16 13:43:21.411830 2018] [:error] [pid 19602] [client 162.158.155.179:64662] PHP 
Catchable fatal error: Object of class HansAdema\\MofhClient\\Client could not be converted to string in /var/www/html/composer/index.php on 
line 14 [Sun Sep 16 13:43:32.591910 2018] [:error] [pid 19149] [client 162.158.155.179:19636] PHP Catchable fatal error: Object of class 
HansAdema\\MofhClient\\Client could not be converted to string in /var/www/html/composer/index.php on line 14 [Sun Sep 16 13:43:38.418231 
2018] [:error] [pid 19150] [client 162.158.155.179:25268] script '/var/www/html/composer/test.php' not found or unable to stat [Sun Sep 16 
13:43:52.440493 2018] [:error] [pid 19151] [client 162.158.155.179:39416] PHP Catchable fatal error: Object of class 
HansAdema\\MofhClient\\Client could not be converted to string in /var/www/html/composer/index.php on line 14 [Sun Sep 16 18:12:10.172341 
2018] [:error] [pid 19148] [client 51.38.12.21:38539] PHP Catchable fatal error: Object of class HansAdema\\MofhClient\\Client could not be 
converted to string in /var/www/html/composer/index.php on line 14 [Mon Sep 17 06:25:03.698652 2018] [mpm_prefork:notice] [pid 8143] AH00171: 
Graceful restart requested, doing restart AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 
127.0.1.1. Set the 'ServerName' directive globally to suppress this message

**Comment by pauladams24** [comment]
But I can't find anything that would explain the error 500, as this is all I think from the previous problem with the namespace.

**Comment by pauladams24** [comment]
Sorry - please could you confirm what exactly is giving you an error 500 as the files seem to not give any error for me just no output.

**Comment by Grendel7** [comment]
The error is right there, staring you in the face.

```
PHP Catchable fatal error: Object of class HansAdema\MofhClient\Client could not be
converted to string in /var/www/html/composer/index.php on line 14 [Sun Sep 16 09:44:50.133577 2018] 
```

Also, I don't get a 500, you do. Because you try to `echo $client`, but `$client` is not something you can echo. Use something like `var_dump` or `print_r` instead.

**Comment by pauladams24** [comment]
Thank you - I now understand. What seems to be the problem is that the `$response` variable is empty. I have tried `print_r($response);` and `echo $response;` but neither output anything. The code works up to this point. Would this be something wrong with sending the request or something with the API as it just returns nothing, not even an error. https://thecoderszone.co.uk/composer/index,php

**Comment by pauladams24** [comment]
I can send the full code again if you want

**Comment by Grendel7** [comment]
Well, sharing the code would help a lot more than sharing the URL. The URL doesn't tell me anything, beyond whether the code works or not (and I think I can guess the answer to that as well by you being here).

**Comment by pauladams24** [comment]
<?php 
error_reporting( E_ALL );
require __DIR__ . '/vendor/autoload.php';
require_once('vendor/autoload.php');
require 'vendor/autoload.php';
use \HansAdema\MofhClient\Client;
if (class_exists('\HansAdema\MofhClient\Client')) { echo "works"; } else { echo "broken"; }
// Create a new API client with your API credentials.
$client = Client::create([
    'apiUsername' => 'XYNzp9wIVGJjc6emkjZSJTLlf4OJf0r389NDCKtwPua67Eyvf8BEBUW1Dc8ZvIXCKAVmSXvSZaRaLuOsUfIa4e5lM44FrIGAUPq7LUGmaQAmN8XaxNQiOlCCDP5csf1qo4lXqLoZCKcfRl8Wy10ZyTZrYrP3x8bONKoZ4bMRDXLMyq8jApPI3hm23vFbSOkCVO2T3NEt2fURgBkI8T55Q09YayOusf9Ogop2iPVgtn7bLxHpC0O2DvU2TESOEId',
    'apiPassword' => 'shE3LX4bimJbUpPTHUsB5701J0mX7YbWPSdPAceR4qE1aNuYaqPTtl6QxHnu7x95JFOjDoHS5bonRfe5uvHIVCYCTojsSmpcgvqkDVAgL3UmLljzqNstz1TpWH12GSnd0rBpEqaeBjBfSOtzU9oys0e77ac1hY9Ju77ZQ6EEOdlWMMvqoiVjfK7INKj4URg8Njay5CT8IxTvx3Veg7m0JPJhlGlIhQI9VVI038Yd4aE5ZdT70ySzpY1C15hUsLl',
    'plan' => 'free', // Optional, you can define it here or define it with the createAccount call.
]);
// Create a request object to create the request.
$request = $client->createAccount([
    'username' => 'abcdefgh', // A unique, 8 character identifier of the account.
    'password' => 'password123', // A password to login to the control panel, FTP and databases.
    'domain' => 'userdomain.example.com', // Can be a subdomain or a custom domain.
    'email' => 'user@example.com', // The email address of the user.
    'plan' => 'my_plan', // Optional, you can submit a hosting plan here or with the Client instantiation.
]);
// Send the API request and keep the response.
$response = $request->send();
echo $response;
print_r($response);
var_dump($response);
// Check whether the request was successful.
if ($response->isSuccessful()) {
   echo 'You can login as: ' . $response->getVpUsername();
} else {
   echo 'Failed to create account: ' . $response->getMessage();
}
?>

**Comment by Grendel7** [comment]
Please forgive me for editing the formatting of your code a little. Note that you can format code blocks properly by using triple backticks.

The issue, I suspect, is that your code crashes on the `echo $response;` line. So `print_r` doesn't dump anything because the code is never executed.

Also, I doubt `require`-ing the autoload.php file three times is going to help with making the code work better.

**Comment by pauladams24** [comment]
I've removed the echo line but still no output.

**Comment by Grendel7** [comment]
Again: does the code still crash? Do you see any error logged?

I'm happy to help you if there are problems using this library. But everything so far just looks like a coding error on your end. Please try to fix these PHP errors first.

**Comment by pauladams24** [comment]
Error: [Thu Sep 20 21:15:53.791004 2018] [:error] [pid 11743] [client 110.164.64.56:30631] PHP Fatal error: Uncaught Error: Call to undefined function HansAdema\\MofhClient\\Message\\simplexml_load_string() in /var/www/html/vendor/hansadema/mofh-client/src/Message/AbstractResponse.php:52\nStack trace:\n#0 /var/www/html/vendor/hansadema/mofh-client/src/Message/AbstractResponse.php(39):HansAdema\\MofhClient\\Message\\AbstractResponse->parseResponse()\n#1 /var/www/html/vendor/hansadema/mofh-client/src/Message/CreateAccountRequest.php(51): HansAdema\\MofhClient\\Message\\AbstractResponse->__construct(Object(HansAdema\\MofhClient\\Message\\CreateAccountRequest), Object(GuzzleHttp\\Psr7\\Response))\n#2 /var/www/html/vendor/hansadema/mofh-client/src/Message/AbstractRequest.php(145): HansAdema\\MofhClient\\Message\\CreateAccountRequest->sendData(Array)\n#3 /var/www/html/test.php(43): HansAdema\\MofhClient\\Message\\AbstractRequest->send()\n#4 {man}\n thrown in /var/www/html/vendor/hansadema/mofh-client/src/Message/AbstractResponse.php on line 52

**Comment by Grendel7** [comment]
https://www.google.com/search?ei=FOekW7X4Dq2YlwS6y7vwBg&q=Uncaught+Error%3A+Call+to+undefined+function+HansAdema%5CMofhClient%5CMessage%5Csimplexml_load_string%28%29&oq=Uncaught+Error%3A+Call+to+undefined+function+HansAdema%5CMofhClient%5CMessage%5Csimplexml_load_string%28%29&gs_l=psy-ab.3...217.862.0.1084.2.2.0.0.0.0.208.208.2-1.1.0....0...1c.1.64.psy-ab..1.0.0....0.YkW6McrUY3c

**Comment by Grendel7** [comment]
Go fix your own PHP stack first.

**Comment by pauladams24** [comment]
Thanks so much for your help. It turned out I had the wrong implementation of PHP installed (I needed PHP FPM) and also was missing the XML module. The API client now works beautifully, thanks for making this. I had one last query (unrelated to the previous problem)  - when you create an account through the standard register.ifastnet.com thing, it tells you the SQL server, and I put this in our database for easy access via the user's client area. How do I find the SQL server (eg sqlxxx.thecoderszone.com) from the API response?

**Comment by Grendel7** [comment]
The API response doesn't have it, and I haven't figured out a way to get it either. If you figure out a way to get the data, please do share it because I would like to know it too.
