### ISSUE TITLE
How to use it in a PHP file?

### ISSUE THREAD

**Issue by ChrisvanChip** [InfinityFreeHosting/mofh-client#35]
Hello,

I know from Infinityfree that it is a webpage. It is secure and it is just hosted on a host. How to do that? I don't have SSH access. I want to create accounts from a form. 

Thank you,
Chris

**Comment by Grendel7** [comment]
Like it said in the README:

> IMPORTANT: THIS LIBRARY IS AIMED AT EXPERIENCED PHP DEVELOPERS. Experience with object-oriented PHP and Composer is required. If you can't use oo-PHP and Composer, don't bother with this library.

This is a Composer library. You can use it like you would any other Composer library. If you don't know what that means or how it works, learn it first. I can't teach you basic programming skills.
