### ISSUE TITLE
Creating a subdomain with the API

### ISSUE THREAD

**Issue by pauladams8** [InfinityFreeHosting/mofh-client#36]
I wanted to know if there was a way to create a subdomain for an existing domain hosted on reseller hosting using the API. 

Eg if example.com is setup on a reseller hosting account with username examp_123456, could I create the subdomain sub.example.com with the same username, using this API (adding the subdomain to the existing account)?

**Comment by Grendel7** [comment]
To my knowledge, all the features which the API offers are implemented in this client. If this software doesn't offer a feature, that means I'm not aware of any API endpoint which provides such functionality. If you know of any API features I'm not aware of, please do share them so I can implement them. But if you're looking for a new feature in the API, you need to ask iFastNet first. If they don't offer a feature, then neither can I.

**Comment by csf30816** [comment]
@pauladams8 I know you probably don't care anymore but you can do this via the cloudflare API if you hook up your domain to cloudflare :)

**Comment by pauladams8** [comment]
@csf30816 Thanks for the suggestion, I am aware of the Cloudflare API, but was asking if there was a way to use the MyOwnFreeHost API to add a subdomain to a hosting account.

**Comment by IceHacks** [comment]
Ah, ok. Sadly there isn't. (Besides maybe just making a new account with the API)
