### ISSUE TITLE
Change email address of hosting account

### ISSUE THREAD

**Issue by pauladams8** [InfinityFreeHosting/mofh-client#37]
Does the API have a function to change the email address of a user's hosting account?

If it does, could it be added as a method to this client?

**Comment by Grendel7** [comment]
All API functions I know of exist in the API are implemented in this client. If the desired functionality (I would like to push email addresses as well) is not available in the API client, you'll need to check with iFastNet whether the functionality is available or can be added.

If there is any API feature which is not implemented here, I'm of course more than happy to implement it.
