### ISSUE TITLE
Questions about the client

### ISSUE THREAD

**Issue by PlanetTheCloud** [InfinityFreeHosting/mofh-client#41]
This is not an actual issue with the client but rather some questions that I had about the client that might be useful for everyone else.

**Comment by PlanetTheCloud** [comment]
So I saw this line:
![image](https://user-images.githubusercontent.com/35788716/54071765-fe983080-42a3-11e9-8626-4f2ece757d0a.png)
What could possibly trigger "The data is not valid."? (in `Tests/GetUserDomainRequestTest.php`)

And also:
![image](https://user-images.githubusercontent.com/35788716/54071779-31422900-42a4-11e9-9878-72b9a34d7218.png)
What could the error possibly be and do you retry the password reset if you receive this message?  (in `Tests/PasswordRequestTest.php`)

**Comment by Grendel7** [comment]
Thank you for submitting this as an issue. A _potential_ error or possibility for improvement in the code is something that could be considered an "issue".

> What could possibly trigger "The data is not valid."?

The exact text is not actually something that is returned by the API. But I've seen the API return a lot of text junk, like a "please try again later" message (which I think might be part of a deployment).

I wanted a generic way to deal with those kinds of weird responses and I needed some dummy text to do that.

 > What could the error possibly be and do you retry the password reset if you receive this message?

From what I can tell, this error is or was being returned when you use the `passwd` call with the current password of the account. Why is why this response is considered successful (the end result is that the password is the desired value).

**Comment by PlanetTheCloud** [comment]
> From what I can tell, this error is or was being returned when you use the `passwd` call with the current password of the account. Why is why this response is considered successful (the end result is that the password is the desired value).

Okay then, I think it's safe show "The password we're changing it to is the same as the current password" or something like that when this happens.

Also, does this line is from the real response:
![image](https://user-images.githubusercontent.com/35788716/54082854-204df200-434e-11e9-83bb-e66b638c3e2e.png)

**Comment by Grendel7** [comment]
> Okay then, I think it's safe show "The password we're changing it to is the same as the current password" or something like that when this happens.

I personally don't care about the difference, but maybe it was not right that I enforced that in the client.

> Also, does this line is from the real response:

Probably, most of the responses have been copy-pasted from responses I recorded from the API.

**Comment by PlanetTheCloud** [comment]
> I personally don't care about the difference, but maybe it was not right that I enforced that in the client.

Okay then, we shall say "Success" no matter what.

**Comment by PlanetTheCloud** [comment]
Is this client used on InfinityFree's Client Area?
If so, how did you handle the errors? If something goes wrong (E.g. server returned something unexpected), do you say "Something went wrong, try again later"?

**Comment by Grendel7** [comment]
Yes, this client is used in InfinityFree.

For the errors, basically, yes. The output is also logged and reported so more error parsing can be implemented.

**Comment by javaskript** [comment]
> Yes, this client is used in InfinityFree.

Slightly off topic of the main issue, but on your subject of InfinityFree - are you also using [Laravel-Auth](https://github.com/jeremykenedy/laravel-auth) as a base for your client panel? I noticed some things appeared similar.

**Comment by Grendel7** [comment]
> Slightly off topic of the main issue

I'd skip the "slightly". You're bumping an old issue on a largely unrelated project to ask a completely unrelated question to what this issue was created for. I'll let it slide for now, but send an email next time. And if you do have more questions about this library, please create a new issue rather than hijacking an existing one.

> are you also using Laravel-Auth as a base for your client panel? I noticed some things appeared similar.

No, for authentication, we don't use anything except for what Laravel offers by default. Registration, authentication and password resets is something Laravel does out of the box, email confirmation and authorization are things Laravel has simple examples for. The only thing custom built is the reCAPTCHA integration, and even that's very simple.

I honestly don't see the benefit of that project. What does it do except for copy-paste `laravel/laravel` and include many of the things optional extras which Laravel (rightfully) doesn't include by default?

**Comment by lavender-sys** [comment]
@HansAdema How exactly do errors work with this client? Can I catch the error somehow and figure out what the error is (without using typo-littered error messages)

**Comment by Grendel7** [comment]
@Dog2puppy Please don't hijack other people's issues to ask your own, completely unrelated questions.

**Comment by lavender-sys** [comment]
Sorry, I thought this issue was dedicated to questions about the client.

**Comment by Grendel7** [comment]
Yes, this issue is dedicated to questions about the client. Specifically, the questions from @PlanetGamingGG about this client.

If you have other questions about this client, open a new issue.

**Comment by PlanetTheCloud** [comment]
Hi, 
To create an account, we need to provide our own `username` to the API. What is this username used for? Also how do InfinityFree generates these usernames?
