### ISSUE TITLE
Existing user info with mofh-client

### ISSUE THREAD

**Issue by javaskript** [InfinityFreeHosting/mofh-client#44]
This is a longshot - but is it possible to migrate over existing MOFH client information into my database using mofh-client? I have created my portal in Laravel, which lists users' hosting accounts, allows for creation of new hosting accounts, etc. To enable the ability of automatic cPanel login, I insert the chosen password on new account creation into my database (using an encryption algorithm and key). I also capture the mofh_username and currently logged-into Laravel user ID. These are inserted into my database as well.

| mofh_username  | laravel_user_id | password_enc | password_key |
| ------------- | ------------- | ------------- | ------------- |
| host_14307665 l  | 1  | 1igSThVvj4EfImIjWg==  | e4d909cd0ca068ffaddf22cbd0 |
| host_26834112  | 2  | uIewK8nB42lOi9==  | 9e107d72bb68d81d35a419d6  |

When a user account is validated (`logged-in laravel_user_id` = `mofh_username->laravel_user_id`), the password_enc and password_key are grabbed from the database, and the decrypted password is injected into the login form which instantly POSTs through to the MOFH cPanel. Is there a better, more secure way of doing this than requiring direct PHP injection of the password into the form? My process works for _new_ user accounts created using the portal (since I associate the MOFH username with the laravel_user_id), but the 150 existing accounts would not be able to have their account logged into from the client panel with this current method. Is there a better way to do this when using mofh-client besides closing all accounts and starting over, ensuring account creation is only done from the client panel in the future?

**Comment by Grendel7** [comment]
> Is there a better, more secure way of doing this than requiring direct PHP injection of the password into the form?

Not really. You can generate login links to the control panel (by reverse engineering the login links in the reseller panel), but those seem to be intended for admins. And you're basically sending the password in the URL (albeit obfuscated), so the security benefits are negligible.

> My process works for new user accounts created using the portal (since I associate the MOFH username with the laravel_user_id), but the 150 existing accounts would not be able to have their account logged into from the client panel with this current method. Is there a better way to do this when using mofh-client besides closing all accounts and starting over, ensuring account creation is only done from the client panel in the future?

Well, there are a couple of problems you run into when importing existing accounts:
- You don't have user information in your database. If or how you can correct that is up to you and your application.
- You don't have any records of the password. You could forcefully reset the passwords of all accounts from your application or urge users to update their own passwords.
- The main domains from the old users are not accepted by the API. The API has hard coded validation rules which ensure that the custom username must be exactly 8 characters. The regular registration form can support usernames between 6 (?) and 15 characters, which the API will simply refuse to accept (I'm not sure if 8 character main domains actually works - I never bothered to test). So even with all the data in your database, you cannot manage the accounts through the API.

I can't say for certain if it's possible or feasible to import existing accounts. I can tell you that it's hard. Whether you want to try or just want to remove or forget these accounts, that's all up to you.

**Comment by javaskript** [comment]
Thanks for the detailed reply @HansAdema. I mostly dabble in frontend design, so I havent done backend work in a long time. It takes a deep thought process to solve some of these issues. Lastly, could you inform me of the best way to generate this 'username' as part of account creation? Initially, I just used the chosen subdomain from the form post data as the username, since these subdomains must be unique anyway. But then I came across the custom domain names. I implemented that, too, but the problem is I have to manually specify a unique username in that case, since the user is not providing a subdomain. I could require a unique username be chosen only if a user also provides their custom domain, but do you also know of any other better way for this handling of the unique username identifier too? At first, I thought the username could have been a generic name, such as "default", each time, since I don't see what this unsername is used for. But then I got a notice that I already registered the username "default" (which of course, forgot it has to be unique) Strange though, since I don't see where this unique username comes into play. Assuredly on MOFH's end then. I notice the username is generated automatically on your host. Perhaps I am overthinking this:

If user chooses subdomain =>
- User fills in subdomain field
- This subdomain field must be unique, is used for the username, and stored in the database as unique_username

If user chooses custom domain =>
- User fills in custom domain field
- User is also then given an additional "username" field, which must be unique, and is stored in the database alongside the other unique_username values.

Basically, if registering with a subdomain, use the subdomain as the unique username. Or, if registering with a custom domain, require the filling in of an additional unique username input field.

But, this way, there might be conflicts when a user using a custom domain name chooses, for example, the username "bookstore", because then a user wanting the subdomain "bookstore" won't be able to register it. As I said, I might be overthinking it - I should just provide a username field for everyone - subdomain or custom domain sign-ups. However, I may be thinking something through incorrectly seeing as the username is generated automatically on your host. I've just been trying to find a way to not require manual entry of the unique username. Please let me know if this solution is logical and in line with what you would do or have done. Thanks again.

**Comment by Grendel7** [comment]
On InfinityFree, the username is randomly generated (using the `Str::random()` function IIRC).

Also, note that:
- The `domain` field MUST be provided, and can be a custom domain or subdomain.
- The provided username will be listed as the main domain, but will not actually be configured to host a website. IIRC, using the provided domain name for the username can cause weird issues, so I would not do that.

Also, in your example, the `bookstore` username would not be accepted, because it's 9 characters instead of 8. This is a result of the API having to much focus on replicating the cPanel API, rather than just offering compatibility with it.

**Comment by javaskript** [comment]
Thank you, your client has worked great (within the limitations of MOFH’s API, which could use a number of improvements). All seems to be working perfectly on my end.

**Comment by lavender-sys** [comment]
@HansAdema On InfinityFree, how do you store hosting account passwords? Do you store it as plain text or is there a way to encrypt it? 

@javaskript I agree, the MOFH API needs a V2, preferably JSON based instead of this strange XML/plain text combo.

**Comment by Grendel7** [comment]
> On InfinityFree, how do you store hosting account passwords? Do you store it as plain text

Passwords are encrypted, but only with a shared master key. Unlike @javaskript, I don't store the encrypt key next to the encrypted password, because that's about as secure as locking a door and hanging they key next to it.

> or is there a way to encrypt it?

Your application stores the data. If you can encrypt stuff, you can encrypt the password as well.

**Comment by lavender-sys** [comment]
Okay. I always just assumed it was stored as plain text because of it only being for the hosting account.
