### ISSUE TITLE
Question about the client and InfinityFree (#2)

### ISSUE THREAD

**Issue by PlanetTheCloud** [InfinityFreeHosting/mofh-client#46]
Since the previous issue had been closed, I'm going to ask my questions here. Let me know if we should just reopen the previous issue.

Hi, I had a few question after a while...

1. To create an account, we need to provide our own username to the API. What is this username used for (as I couldn't find it on MOFH Reseller Panel)? Also how do InfinityFree generates these usernames? And is it safe if we just use increments to generate this usernames?

2. How to retrieve the main domain? As far as I know, https://myprohost.ga uses this client to interface with MOFH's API and it has a Domain and Main Domain column as seen in the screenshot below:
![image](https://user-images.githubusercontent.com/35788716/64061208-803c9b80-cc01-11e9-9060-a239ca1666d2.png)
I assume the domain column is filled with the domain supplied during account creation.

**Comment by lavender-sys** [comment]
The 8 character username field is just used for the main domain. I think that some methods of the api require this username instead of the vpusername, so storing it is important. For generating them I just use Laravel’s Str::random and I don’t bother to check if it’s unique in the database beforehand. Increments would probably work too. 

Because of the main domain just being the username, I just store the username part and then in the view I add the .undisk.ga.

**Comment by PlanetTheCloud** [comment]
Okay, thank you for clarifying about what it is used for and how you generated it. 
I still wanted to know how IF generates those usernames because IF has lot's of users and the username must be unique.

About the Main Domain tho, how can you be sure that the domain will end in `undisk.ga` instead of `nixit.ga` in my case? I checked InfinityFree has their main domain ends in `.rf.gd` for my accounts with `.rf.gd` subdomain.

**Comment by lavender-sys** [comment]
If I remember right, Hans mentioned on the old hosters.cc forum (now dead) that he used Str::random. This is actually the way that I found out about Laravel. 

The main domain is based off of which API keys are used. If I use the api keys for nixit.ga then it’s a nixit.ga main domain. For undisk.ga keys it’s an undisk.ga main domain. InfinityFree might handle this differently though.

**Comment by Grendel7** [comment]
Initially, I generated the main domain based on the local database primary key, but that blew up in my face once when I setup a copy of the production database for development and created an account with that. Random generation is easier and less error prone.

There were times when I used separate API key pairs for all the different subdomains, but now I use one API key pair for all accounts. I like the easy of managing only a single key pair, but it's mostly personal preference as to what you should use.
