### ISSUE TITLE
Find reseller of unavailable domain

### ISSUE THREAD

**Issue by pauladams8** [InfinityFreeHosting/mofh-client#48]
I noticed on InfinityFree with your domain availability validation you return the reseller domain name when a domain is taken.

How do you do this as I don't think it's returned in the API response  from the `checkavailable` endpoint?

**Comment by pauladams8** [comment]
Example: 

> The selected custom domain is already in use on byet.org. Please remove the custom domain from your account at byet.org before you can host it on InfinityFree.

**Comment by Grendel7** [comment]
The API doesn't return which reseller the domain belongs to. But you can figure it out through the DNS of the domain. If you do an SOA lookup on the domain on the free hosting nameservers, you'll see the reseller domain the queried domain belongs to.

**Comment by pauladams8** [comment]
Thank you
