### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by NamVr** [InfinityFreeHosting/mofh-client#50]
Hi!

As I am completely new in php, I want to learn how can I get started.

I am ready to invest my time in learning php laravel anything, I have plenty of time.
But I want to make a front end with this API client. Like people first register their accounts then sub accounts will be registered with the actual hosting (as like as infinity's)
I want to learn. Can someone help me what all things I need to do? I have a windows 10 pc.

**Comment by Grendel7** [comment]
If you want to learn PHP, there are many tutorials, classes and guides available on line. Just search the web for help. And don't dump this question in the issue tracker of a library.

**Comment by NamVr** [comment]
Yeah I searched, but I see none of them related to MOFH.
What should I do?

**Comment by Grendel7** [comment]
Start by learning software development. If you know software development, figuring out how to build software to work with MOFH is easy. Just don't expect someone to spoon feed you the exact lines of code to type to build the exact product you want. Or at least, don't expect me to do this for you.
