### ISSUE TITLE
How do you handle account status

### ISSUE THREAD

**Issue by Sarveshmrao** [InfinityFreeHosting/mofh-client#51]
This is not an actual issue with the client but rather some questions that I had about the client that might be useful for everyone else.
Hoe do you handle the account status. Like suspended, active, closed etc. also how do you mention suspension is because of spam, suspension is because of inactivity, the suspension is because of MySQL overuse etc. I don't see any function for that in this client.

**Comment by Grendel7** [comment]
The exact logic for account statuses in the InfinityFree is quite elaborate, very opinionated and deeply tied to my specific implementation. The API client is intended to be generic, so my specific logic and opinions are left out of it.

But as a few general tips:
- The create account, suspend and reactivate calls all take a while to take effect. I would suggest to fire the API call, and then put the account in a locked/processing/pending state until the webhook comes in.
- The webhook also contains the exact suspension reason from the hosting platform. You should record this reason.
- Given the reason/comments from the webhook, you can use string matching or regular expression to identify known types of suspensions. Studying previously recording reasons is extremely useful to identify patterns.

**Comment by Sarveshmrao** [comment]
Hey! 
Sorry for too late to reply. 

Thanks for your tips. Do you have any idea of what the params the webhook gives and the types of status it gives. 

Then how do you manage the API Key pairs? It is not that much easy to manage the API Keys for each and every domain. How does IF handle this?

**Comment by Grendel7** [comment]
> Do you have any idea of what the params the webhook gives and the types of status it gives.

Of course I know, but I don't have descriptions ready to use. I'll try and write something about that when I have time.

If you don't want to wait for that, you can just play around with the API and send it to some kind of HTTP request catcher and analyze it yourself.

> Then how do you manage the API Key pairs? It is not that much easy to manage the API Keys for each and every domain. How does IF handle this?

InfinityFree uses a single API key pair. You can create free subdomains with your own domain names with any key pair of any reseller domain. The only thing to note is that things like nameservers, MX records and main domains all use the specific reseller domain.

**Comment by Sarveshmrao** [comment]
Fine. If you have time and if possible please document the responses of the API and yeah I tried recording it but I was able to record only some of them. 


This is what I understood from yours. 
You use same API Key pair and just change the main Domain etc while creating accounts. Am I right?

**Comment by Grendel7** [comment]
>  You use same API Key pair and just change the main Domain etc while creating accounts. Am I right?

Yes.
